server:
  port: 8888

spring:
  application:
    name: config-server
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/study/MSA/native-file-repo
        git:
#          uri: file://../../../git-local-repo
#          uri: file:///Users/user/eclipse-workspace/MSA/git-local-repo #home
#          uri: file:///Users/kimdaeho/study/MSA/git-local-repo #SIL
          uri: https://github.com/zzangisdaeho/git-local-repo.git
          default-label: main
#          username: [write username]
#          password: [write password]
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
